name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheel-*
          path: dist

      - uses: pypa/gh-action-pypi-publish@v2
        with:
          packages-dir: dist/
